// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: system.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"requestId"
	// request_id 是本次请求的链路追踪 ID，由中间件生成或透传。
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"requestId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"message"
	// message 表示当前接口的探活结果，正常情况下返回 pong。
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	// @inject_tag: json:"service"
	// service 表示响应本次请求的后端服务名。
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service"`
	// @inject_tag: json:"environment"
	// environment 表示当前服务运行环境，例如 development、test、production。
	Environment string `protobuf:"bytes,3,opt,name=environment,proto3" json:"environment"`
	// @inject_tag: json:"requestId"
	// request_id 用于前后端联调和线上日志排查。
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"requestId"`
	// @inject_tag: json:"timestamp"
	// timestamp 表示服务生成响应时的 Unix 秒级时间戳。
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *PingResponse) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *PingResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SloganRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"requestId"
	// request_id 是本次请求的链路追踪 ID，由中间件生成或透传。
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"requestId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloganRequest) Reset() {
	*x = SloganRequest{}
	mi := &file_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloganRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloganRequest) ProtoMessage() {}

func (x *SloganRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloganRequest.ProtoReflect.Descriptor instead.
func (*SloganRequest) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{2}
}

func (x *SloganRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type SloganResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"slogan"
	// slogan 表示 Two-To 项目面向用户展示的核心口号。
	Slogan string `protobuf:"bytes,1,opt,name=slogan,proto3" json:"slogan"`
	// @inject_tag: json:"requestId"
	// request_id 用于前后端联调和线上日志排查。
	RequestId     string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"requestId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SloganResponse) Reset() {
	*x = SloganResponse{}
	mi := &file_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SloganResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SloganResponse) ProtoMessage() {}

func (x *SloganResponse) ProtoReflect() protoreflect.Message {
	mi := &file_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SloganResponse.ProtoReflect.Descriptor instead.
func (*SloganResponse) Descriptor() ([]byte, []int) {
	return file_system_proto_rawDescGZIP(), []int{3}
}

func (x *SloganResponse) GetSlogan() string {
	if x != nil {
		return x.Slogan
	}
	return ""
}

func (x *SloganResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_system_proto protoreflect.FileDescriptor

const file_system_proto_rawDesc = "" +
	"\n" +
	"\fsystem.proto\x12\x0ftwoto.system.v1\",\n" +
	"\vPingRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\xa1\x01\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12 \n" +
	"\venvironment\x18\x03 \x01(\tR\venvironment\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\".\n" +
	"\rSloganRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"G\n" +
	"\x0eSloganResponse\x12\x16\n" +
	"\x06slogan\x18\x01 \x01(\tR\x06slogan\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestIdB/Z-github.com/zxh3032/two-to/backend/proto;protob\x06proto3"

var (
	file_system_proto_rawDescOnce sync.Once
	file_system_proto_rawDescData []byte
)

func file_system_proto_rawDescGZIP() []byte {
	file_system_proto_rawDescOnce.Do(func() {
		file_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)))
	})
	return file_system_proto_rawDescData
}

var file_system_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_system_proto_goTypes = []any{
	(*PingRequest)(nil),    // 0: twoto.system.v1.PingRequest
	(*PingResponse)(nil),   // 1: twoto.system.v1.PingResponse
	(*SloganRequest)(nil),  // 2: twoto.system.v1.SloganRequest
	(*SloganResponse)(nil), // 3: twoto.system.v1.SloganResponse
}
var file_system_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_proto_init() }
func file_system_proto_init() {
	if File_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_proto_rawDesc), len(file_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_system_proto_goTypes,
		DependencyIndexes: file_system_proto_depIdxs,
		MessageInfos:      file_system_proto_msgTypes,
	}.Build()
	File_system_proto = out.File
	file_system_proto_goTypes = nil
	file_system_proto_depIdxs = nil
}
