// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"nickname"
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	// @inject_tag: json:"status"
	Status        int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"petStage"
	PetStage string `protobuf:"bytes,1,opt,name=pet_stage,json=petStage,proto3" json:"petStage"`
	// @inject_tag: json:"interestedPetTypes"
	InterestedPetTypes []string `protobuf:"bytes,2,rep,name=interested_pet_types,json=interestedPetTypes,proto3" json:"interestedPetTypes"`
	// @inject_tag: json:"petExperience"
	PetExperience string `protobuf:"bytes,3,opt,name=pet_experience,json=petExperience,proto3" json:"petExperience"`
	// @inject_tag: json:"dailyCompanyTime"
	DailyCompanyTime string `protobuf:"bytes,4,opt,name=daily_company_time,json=dailyCompanyTime,proto3" json:"dailyCompanyTime"`
	// @inject_tag: json:"livingSituation"
	LivingSituation string `protobuf:"bytes,5,opt,name=living_situation,json=livingSituation,proto3" json:"livingSituation"`
	// @inject_tag: json:"petConstraints"
	PetConstraints []string `protobuf:"bytes,6,rep,name=pet_constraints,json=petConstraints,proto3" json:"petConstraints"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfile) GetPetStage() string {
	if x != nil {
		return x.PetStage
	}
	return ""
}

func (x *UserProfile) GetInterestedPetTypes() []string {
	if x != nil {
		return x.InterestedPetTypes
	}
	return nil
}

func (x *UserProfile) GetPetExperience() string {
	if x != nil {
		return x.PetExperience
	}
	return ""
}

func (x *UserProfile) GetDailyCompanyTime() string {
	if x != nil {
		return x.DailyCompanyTime
	}
	return ""
}

func (x *UserProfile) GetLivingSituation() string {
	if x != nil {
		return x.LivingSituation
	}
	return ""
}

func (x *UserProfile) GetPetConstraints() []string {
	if x != nil {
		return x.PetConstraints
	}
	return nil
}

type UserIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"identityType"
	IdentityType string `protobuf:"bytes,2,opt,name=identity_type,json=identityType,proto3" json:"identityType"`
	// @inject_tag: json:"identityValue"
	IdentityValue string `protobuf:"bytes,3,opt,name=identity_value,json=identityValue,proto3" json:"identityValue"`
	// @inject_tag: json:"maskedValue"
	MaskedValue string `protobuf:"bytes,4,opt,name=masked_value,json=maskedValue,proto3" json:"maskedValue"`
	// @inject_tag: json:"verifyTime"
	VerifyTime    int64 `protobuf:"varint,5,opt,name=verify_time,json=verifyTime,proto3" json:"verifyTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdentity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserIdentity) GetIdentityType() string {
	if x != nil {
		return x.IdentityType
	}
	return ""
}

func (x *UserIdentity) GetIdentityValue() string {
	if x != nil {
		return x.IdentityValue
	}
	return ""
}

func (x *UserIdentity) GetMaskedValue() string {
	if x != nil {
		return x.MaskedValue
	}
	return ""
}

func (x *UserIdentity) GetVerifyTime() int64 {
	if x != nil {
		return x.VerifyTime
	}
	return 0
}

type UserSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"deviceName"
	DeviceName string `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"deviceName"`
	// @inject_tag: json:"status"
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"lastActiveTime"
	LastActiveTime int64 `protobuf:"varint,4,opt,name=last_active_time,json=lastActiveTime,proto3" json:"lastActiveTime"`
	// @inject_tag: json:"expireTime"
	ExpireTime int64 `protobuf:"varint,5,opt,name=expire_time,json=expireTime,proto3" json:"expireTime"`
	// @inject_tag: json:"current"
	Current       bool `protobuf:"varint,6,opt,name=current,proto3" json:"current"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSession) Reset() {
	*x = UserSession{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSession) ProtoMessage() {}

func (x *UserSession) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSession.ProtoReflect.Descriptor instead.
func (*UserSession) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserSession) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSession) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *UserSession) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserSession) GetLastActiveTime() int64 {
	if x != nil {
		return x.LastActiveTime
	}
	return 0
}

func (x *UserSession) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *UserSession) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

type CaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaRequest) Reset() {
	*x = CaptchaRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaRequest) ProtoMessage() {}

func (x *CaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaRequest.ProtoReflect.Descriptor instead.
func (*CaptchaRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

type CaptchaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"captchaId"
	CaptchaId string `protobuf:"bytes,1,opt,name=captcha_id,json=captchaId,proto3" json:"captchaId"`
	// @inject_tag: json:"imageBase64"
	ImageBase64 string `protobuf:"bytes,2,opt,name=image_base64,json=imageBase64,proto3" json:"imageBase64"`
	// @inject_tag: json:"expiresIn"
	ExpiresIn     int64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expiresIn"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaResponse) Reset() {
	*x = CaptchaResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaResponse) ProtoMessage() {}

func (x *CaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaResponse.ProtoReflect.Descriptor instead.
func (*CaptchaResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *CaptchaResponse) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaResponse) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

func (x *CaptchaResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type SendCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"codeType"
	CodeType string `protobuf:"bytes,1,opt,name=code_type,json=codeType,proto3" json:"codeType"`
	// @inject_tag: json:"scene"
	Scene string `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene"`
	// @inject_tag: json:"target"
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target"`
	// @inject_tag: json:"captchaId"
	CaptchaId string `protobuf:"bytes,4,opt,name=captcha_id,json=captchaId,proto3" json:"captchaId"`
	// @inject_tag: json:"captchaCode"
	CaptchaCode   string `protobuf:"bytes,5,opt,name=captcha_code,json=captchaCode,proto3" json:"captchaCode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeRequest) Reset() {
	*x = SendCodeRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeRequest) ProtoMessage() {}

func (x *SendCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeRequest.ProtoReflect.Descriptor instead.
func (*SendCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *SendCodeRequest) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

func (x *SendCodeRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *SendCodeRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SendCodeRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *SendCodeRequest) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

type SendCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"cooldownSeconds"
	CooldownSeconds int64 `protobuf:"varint,1,opt,name=cooldown_seconds,json=cooldownSeconds,proto3" json:"cooldownSeconds"`
	// @inject_tag: json:"expiresIn"
	ExpiresIn     int64 `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expiresIn"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCodeResponse) Reset() {
	*x = SendCodeResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCodeResponse) ProtoMessage() {}

func (x *SendCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCodeResponse.ProtoReflect.Descriptor instead.
func (*SendCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *SendCodeResponse) GetCooldownSeconds() int64 {
	if x != nil {
		return x.CooldownSeconds
	}
	return 0
}

func (x *SendCodeResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type EmailLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	// @inject_tag: json:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	// @inject_tag: json:"captchaId"
	CaptchaId string `protobuf:"bytes,3,opt,name=captcha_id,json=captchaId,proto3" json:"captchaId"`
	// @inject_tag: json:"captchaCode"
	CaptchaCode   string `protobuf:"bytes,4,opt,name=captcha_code,json=captchaCode,proto3" json:"captchaCode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLoginRequest) Reset() {
	*x = EmailLoginRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginRequest) ProtoMessage() {}

func (x *EmailLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginRequest.ProtoReflect.Descriptor instead.
func (*EmailLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *EmailLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EmailLoginRequest) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *EmailLoginRequest) GetCaptchaCode() string {
	if x != nil {
		return x.CaptchaCode
	}
	return ""
}

type EmailLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"accessToken"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"accessToken"`
	// @inject_tag: json:"accessTokenExpiresIn"
	AccessTokenExpiresIn int64 `protobuf:"varint,2,opt,name=access_token_expires_in,json=accessTokenExpiresIn,proto3" json:"accessTokenExpiresIn"`
	// @inject_tag: json:"refreshToken"
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken"`
	// @inject_tag: json:"refreshTokenExpiresIn"
	RefreshTokenExpiresIn int64 `protobuf:"varint,4,opt,name=refresh_token_expires_in,json=refreshTokenExpiresIn,proto3" json:"refreshTokenExpiresIn"`
	// @inject_tag: json:"user"
	User          *UserInfo `protobuf:"bytes,5,opt,name=user,proto3" json:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailLoginResponse) Reset() {
	*x = EmailLoginResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailLoginResponse) ProtoMessage() {}

func (x *EmailLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailLoginResponse.ProtoReflect.Descriptor instead.
func (*EmailLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *EmailLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *EmailLoginResponse) GetAccessTokenExpiresIn() int64 {
	if x != nil {
		return x.AccessTokenExpiresIn
	}
	return 0
}

func (x *EmailLoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *EmailLoginResponse) GetRefreshTokenExpiresIn() int64 {
	if x != nil {
		return x.RefreshTokenExpiresIn
	}
	return 0
}

func (x *EmailLoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type PhoneLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"phone"
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone"`
	// @inject_tag: json:"smsCode"
	SmsCode       string `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"smsCode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginRequest) Reset() {
	*x = PhoneLoginRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginRequest) ProtoMessage() {}

func (x *PhoneLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginRequest.ProtoReflect.Descriptor instead.
func (*PhoneLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *PhoneLoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PhoneLoginRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type EmailRegisterVerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	// @inject_tag: json:"password"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	// @inject_tag: json:"emailCode"
	EmailCode     string `protobuf:"bytes,3,opt,name=email_code,json=emailCode,proto3" json:"emailCode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRegisterVerifyRequest) Reset() {
	*x = EmailRegisterVerifyRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRegisterVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRegisterVerifyRequest) ProtoMessage() {}

func (x *EmailRegisterVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRegisterVerifyRequest.ProtoReflect.Descriptor instead.
func (*EmailRegisterVerifyRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *EmailRegisterVerifyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailRegisterVerifyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EmailRegisterVerifyRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

type EmailRegisterVerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profileSetupToken"
	ProfileSetupToken string `protobuf:"bytes,1,opt,name=profile_setup_token,json=profileSetupToken,proto3" json:"profileSetupToken"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmailRegisterVerifyResponse) Reset() {
	*x = EmailRegisterVerifyResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRegisterVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRegisterVerifyResponse) ProtoMessage() {}

func (x *EmailRegisterVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRegisterVerifyResponse.ProtoReflect.Descriptor instead.
func (*EmailRegisterVerifyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *EmailRegisterVerifyResponse) GetProfileSetupToken() string {
	if x != nil {
		return x.ProfileSetupToken
	}
	return ""
}

type CompleteProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profileSetupToken"
	ProfileSetupToken string `protobuf:"bytes,1,opt,name=profile_setup_token,json=profileSetupToken,proto3" json:"profileSetupToken"`
	// @inject_tag: json:"nickname"
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	// @inject_tag: json:"petStage"
	PetStage string `protobuf:"bytes,3,opt,name=pet_stage,json=petStage,proto3" json:"petStage"`
	// @inject_tag: json:"interestedPetTypes"
	InterestedPetTypes []string `protobuf:"bytes,4,rep,name=interested_pet_types,json=interestedPetTypes,proto3" json:"interestedPetTypes"`
	// @inject_tag: json:"petExperience"
	PetExperience string `protobuf:"bytes,5,opt,name=pet_experience,json=petExperience,proto3" json:"petExperience"`
	// @inject_tag: json:"dailyCompanyTime"
	DailyCompanyTime string `protobuf:"bytes,6,opt,name=daily_company_time,json=dailyCompanyTime,proto3" json:"dailyCompanyTime"`
	// @inject_tag: json:"livingSituation"
	LivingSituation string `protobuf:"bytes,7,opt,name=living_situation,json=livingSituation,proto3" json:"livingSituation"`
	// @inject_tag: json:"petConstraints"
	PetConstraints []string `protobuf:"bytes,8,rep,name=pet_constraints,json=petConstraints,proto3" json:"petConstraints"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteProfileRequest) Reset() {
	*x = CompleteProfileRequest{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteProfileRequest) ProtoMessage() {}

func (x *CompleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteProfileRequest.ProtoReflect.Descriptor instead.
func (*CompleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteProfileRequest) GetProfileSetupToken() string {
	if x != nil {
		return x.ProfileSetupToken
	}
	return ""
}

func (x *CompleteProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CompleteProfileRequest) GetPetStage() string {
	if x != nil {
		return x.PetStage
	}
	return ""
}

func (x *CompleteProfileRequest) GetInterestedPetTypes() []string {
	if x != nil {
		return x.InterestedPetTypes
	}
	return nil
}

func (x *CompleteProfileRequest) GetPetExperience() string {
	if x != nil {
		return x.PetExperience
	}
	return ""
}

func (x *CompleteProfileRequest) GetDailyCompanyTime() string {
	if x != nil {
		return x.DailyCompanyTime
	}
	return ""
}

func (x *CompleteProfileRequest) GetLivingSituation() string {
	if x != nil {
		return x.LivingSituation
	}
	return ""
}

func (x *CompleteProfileRequest) GetPetConstraints() []string {
	if x != nil {
		return x.PetConstraints
	}
	return nil
}

type CompleteProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"accessToken"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"accessToken"`
	// @inject_tag: json:"accessTokenExpiresIn"
	AccessTokenExpiresIn int64 `protobuf:"varint,2,opt,name=access_token_expires_in,json=accessTokenExpiresIn,proto3" json:"accessTokenExpiresIn"`
	// @inject_tag: json:"refreshToken"
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken"`
	// @inject_tag: json:"refreshTokenExpiresIn"
	RefreshTokenExpiresIn int64 `protobuf:"varint,4,opt,name=refresh_token_expires_in,json=refreshTokenExpiresIn,proto3" json:"refreshTokenExpiresIn"`
	// @inject_tag: json:"user"
	User          *UserInfo `protobuf:"bytes,5,opt,name=user,proto3" json:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteProfileResponse) Reset() {
	*x = CompleteProfileResponse{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteProfileResponse) ProtoMessage() {}

func (x *CompleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteProfileResponse.ProtoReflect.Descriptor instead.
func (*CompleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteProfileResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CompleteProfileResponse) GetAccessTokenExpiresIn() int64 {
	if x != nil {
		return x.AccessTokenExpiresIn
	}
	return 0
}

func (x *CompleteProfileResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CompleteProfileResponse) GetRefreshTokenExpiresIn() int64 {
	if x != nil {
		return x.RefreshTokenExpiresIn
	}
	return 0
}

func (x *CompleteProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"accessToken"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"accessToken"`
	// @inject_tag: json:"accessTokenExpiresIn"
	AccessTokenExpiresIn int64 `protobuf:"varint,2,opt,name=access_token_expires_in,json=accessTokenExpiresIn,proto3" json:"accessTokenExpiresIn"`
	// @inject_tag: json:"refreshToken"
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken"`
	// @inject_tag: json:"refreshTokenExpiresIn"
	RefreshTokenExpiresIn int64 `protobuf:"varint,4,opt,name=refresh_token_expires_in,json=refreshTokenExpiresIn,proto3" json:"refreshTokenExpiresIn"`
	// @inject_tag: json:"user"
	User          *UserInfo `protobuf:"bytes,5,opt,name=user,proto3" json:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetAccessTokenExpiresIn() int64 {
	if x != nil {
		return x.AccessTokenExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshTokenExpiresIn() int64 {
	if x != nil {
		return x.RefreshTokenExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type PhoneLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"requiresProfileSetup"
	RequiresProfileSetup bool `protobuf:"varint,1,opt,name=requires_profile_setup,json=requiresProfileSetup,proto3" json:"requiresProfileSetup"`
	// @inject_tag: json:"profileSetupToken"
	ProfileSetupToken string `protobuf:"bytes,2,opt,name=profile_setup_token,json=profileSetupToken,proto3" json:"profileSetupToken"`
	// @inject_tag: json:"auth"
	Auth          *LoginResponse `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneLoginResponse) Reset() {
	*x = PhoneLoginResponse{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneLoginResponse) ProtoMessage() {}

func (x *PhoneLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneLoginResponse.ProtoReflect.Descriptor instead.
func (*PhoneLoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *PhoneLoginResponse) GetRequiresProfileSetup() bool {
	if x != nil {
		return x.RequiresProfileSetup
	}
	return false
}

func (x *PhoneLoginResponse) GetProfileSetupToken() string {
	if x != nil {
		return x.ProfileSetupToken
	}
	return ""
}

func (x *PhoneLoginResponse) GetAuth() *LoginResponse {
	if x != nil {
		return x.Auth
	}
	return nil
}

type RefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"refreshToken"
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"accessToken"
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"accessToken"`
	// @inject_tag: json:"accessTokenExpiresIn"
	AccessTokenExpiresIn int64 `protobuf:"varint,2,opt,name=access_token_expires_in,json=accessTokenExpiresIn,proto3" json:"accessTokenExpiresIn"`
	// @inject_tag: json:"refreshToken"
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken"`
	// @inject_tag: json:"refreshTokenExpiresIn"
	RefreshTokenExpiresIn int64 `protobuf:"varint,4,opt,name=refresh_token_expires_in,json=refreshTokenExpiresIn,proto3" json:"refreshTokenExpiresIn"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetAccessTokenExpiresIn() int64 {
	if x != nil {
		return x.AccessTokenExpiresIn
	}
	return 0
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshTokenExpiresIn() int64 {
	if x != nil {
		return x.RefreshTokenExpiresIn
	}
	return 0
}

type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"refreshToken"
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refreshToken"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

type ForgotPasswordVerifyCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"identityType"
	IdentityType string `protobuf:"bytes,1,opt,name=identity_type,json=identityType,proto3" json:"identityType"`
	// @inject_tag: json:"identityValue"
	IdentityValue string `protobuf:"bytes,2,opt,name=identity_value,json=identityValue,proto3" json:"identityValue"`
	// @inject_tag: json:"code"
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordVerifyCodeRequest) Reset() {
	*x = ForgotPasswordVerifyCodeRequest{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordVerifyCodeRequest) ProtoMessage() {}

func (x *ForgotPasswordVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *ForgotPasswordVerifyCodeRequest) GetIdentityType() string {
	if x != nil {
		return x.IdentityType
	}
	return ""
}

func (x *ForgotPasswordVerifyCodeRequest) GetIdentityValue() string {
	if x != nil {
		return x.IdentityValue
	}
	return ""
}

func (x *ForgotPasswordVerifyCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ForgotPasswordVerifyCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"resetToken"
	ResetToken    string `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"resetToken"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordVerifyCodeResponse) Reset() {
	*x = ForgotPasswordVerifyCodeResponse{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordVerifyCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordVerifyCodeResponse) ProtoMessage() {}

func (x *ForgotPasswordVerifyCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordVerifyCodeResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordVerifyCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *ForgotPasswordVerifyCodeResponse) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

type ForgotPasswordResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"resetToken"
	ResetToken string `protobuf:"bytes,1,opt,name=reset_token,json=resetToken,proto3" json:"resetToken"`
	// @inject_tag: json:"newPassword"
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"newPassword"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResetRequest) Reset() {
	*x = ForgotPasswordResetRequest{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResetRequest) ProtoMessage() {}

func (x *ForgotPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *ForgotPasswordResetRequest) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

func (x *ForgotPasswordResetRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ForgotPasswordResetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResetResponse) Reset() {
	*x = ForgotPasswordResetResponse{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResetResponse) ProtoMessage() {}

func (x *ForgotPasswordResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResetResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResetResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

type AccountMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountMeRequest) Reset() {
	*x = AccountMeRequest{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMeRequest) ProtoMessage() {}

func (x *AccountMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMeRequest.ProtoReflect.Descriptor instead.
func (*AccountMeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

type AccountMeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user"
	User *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	// @inject_tag: json:"profile"
	Profile *UserProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile"`
	// @inject_tag: json:"identities"
	Identities    []*UserIdentity `protobuf:"bytes,3,rep,name=identities,proto3" json:"identities"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountMeResponse) Reset() {
	*x = AccountMeResponse{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMeResponse) ProtoMessage() {}

func (x *AccountMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMeResponse.ProtoReflect.Descriptor instead.
func (*AccountMeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *AccountMeResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AccountMeResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *AccountMeResponse) GetIdentities() []*UserIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"nickname"
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname"`
	// @inject_tag: json:"petStage"
	PetStage string `protobuf:"bytes,2,opt,name=pet_stage,json=petStage,proto3" json:"petStage"`
	// @inject_tag: json:"interestedPetTypes"
	InterestedPetTypes []string `protobuf:"bytes,3,rep,name=interested_pet_types,json=interestedPetTypes,proto3" json:"interestedPetTypes"`
	// @inject_tag: json:"petExperience"
	PetExperience string `protobuf:"bytes,4,opt,name=pet_experience,json=petExperience,proto3" json:"petExperience"`
	// @inject_tag: json:"dailyCompanyTime"
	DailyCompanyTime string `protobuf:"bytes,5,opt,name=daily_company_time,json=dailyCompanyTime,proto3" json:"dailyCompanyTime"`
	// @inject_tag: json:"livingSituation"
	LivingSituation string `protobuf:"bytes,6,opt,name=living_situation,json=livingSituation,proto3" json:"livingSituation"`
	// @inject_tag: json:"petConstraints"
	PetConstraints []string `protobuf:"bytes,7,rep,name=pet_constraints,json=petConstraints,proto3" json:"petConstraints"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetPetStage() string {
	if x != nil {
		return x.PetStage
	}
	return ""
}

func (x *UpdateProfileRequest) GetInterestedPetTypes() []string {
	if x != nil {
		return x.InterestedPetTypes
	}
	return nil
}

func (x *UpdateProfileRequest) GetPetExperience() string {
	if x != nil {
		return x.PetExperience
	}
	return ""
}

func (x *UpdateProfileRequest) GetDailyCompanyTime() string {
	if x != nil {
		return x.DailyCompanyTime
	}
	return ""
}

func (x *UpdateProfileRequest) GetLivingSituation() string {
	if x != nil {
		return x.LivingSituation
	}
	return ""
}

func (x *UpdateProfileRequest) GetPetConstraints() []string {
	if x != nil {
		return x.PetConstraints
	}
	return nil
}

type UpdateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user"
	User *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`
	// @inject_tag: json:"profile"
	Profile *UserProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile"`
	// @inject_tag: json:"identities"
	Identities    []*UserIdentity `protobuf:"bytes,3,rep,name=identities,proto3" json:"identities"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateProfileResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UpdateProfileResponse) GetIdentities() []*UserIdentity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type UpdateEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	// @inject_tag: json:"emailCode"
	EmailCode     string `protobuf:"bytes,2,opt,name=email_code,json=emailCode,proto3" json:"emailCode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateEmailRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

type UpdateEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailResponse) Reset() {
	*x = UpdateEmailResponse{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailResponse) ProtoMessage() {}

func (x *UpdateEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

type UpdatePhoneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"phone"
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone"`
	// @inject_tag: json:"smsCode"
	SmsCode       string `protobuf:"bytes,2,opt,name=sms_code,json=smsCode,proto3" json:"smsCode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePhoneRequest) Reset() {
	*x = UpdatePhoneRequest{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhoneRequest) ProtoMessage() {}

func (x *UpdatePhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhoneRequest.ProtoReflect.Descriptor instead.
func (*UpdatePhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

func (x *UpdatePhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdatePhoneRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type UpdatePhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePhoneResponse) Reset() {
	*x = UpdatePhoneResponse{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhoneResponse) ProtoMessage() {}

func (x *UpdatePhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhoneResponse.ProtoReflect.Descriptor instead.
func (*UpdatePhoneResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

type UnbindEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"currentPassword"
	CurrentPassword string `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"currentPassword"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnbindEmailRequest) Reset() {
	*x = UnbindEmailRequest{}
	mi := &file_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindEmailRequest) ProtoMessage() {}

func (x *UnbindEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindEmailRequest.ProtoReflect.Descriptor instead.
func (*UnbindEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{33}
}

func (x *UnbindEmailRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

type UnbindEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindEmailResponse) Reset() {
	*x = UnbindEmailResponse{}
	mi := &file_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindEmailResponse) ProtoMessage() {}

func (x *UnbindEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindEmailResponse.ProtoReflect.Descriptor instead.
func (*UnbindEmailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{34}
}

type UnbindPhoneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"currentPassword"
	CurrentPassword string `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"currentPassword"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnbindPhoneRequest) Reset() {
	*x = UnbindPhoneRequest{}
	mi := &file_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindPhoneRequest) ProtoMessage() {}

func (x *UnbindPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindPhoneRequest.ProtoReflect.Descriptor instead.
func (*UnbindPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{35}
}

func (x *UnbindPhoneRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

type UnbindPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindPhoneResponse) Reset() {
	*x = UnbindPhoneResponse{}
	mi := &file_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindPhoneResponse) ProtoMessage() {}

func (x *UnbindPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindPhoneResponse.ProtoReflect.Descriptor instead.
func (*UnbindPhoneResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{36}
}

type UpdatePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"currentPassword"
	CurrentPassword string `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"currentPassword"`
	// @inject_tag: json:"newPassword"
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"newPassword"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{37}
}

func (x *UpdatePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *UpdatePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordResponse) Reset() {
	*x = UpdatePasswordResponse{}
	mi := &file_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordResponse) ProtoMessage() {}

func (x *UpdatePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordResponse.ProtoReflect.Descriptor instead.
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{38}
}

type SessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionsRequest) Reset() {
	*x = SessionsRequest{}
	mi := &file_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsRequest) ProtoMessage() {}

func (x *SessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsRequest.ProtoReflect.Descriptor instead.
func (*SessionsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{39}
}

type SessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"sessions"
	Sessions []*UserSession `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions"`
	// @inject_tag: json:"currentSessionId"
	CurrentSessionId int64 `protobuf:"varint,2,opt,name=current_session_id,json=currentSessionId,proto3" json:"currentSessionId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionsResponse) Reset() {
	*x = SessionsResponse{}
	mi := &file_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsResponse) ProtoMessage() {}

func (x *SessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsResponse.ProtoReflect.Descriptor instead.
func (*SessionsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{40}
}

func (x *SessionsResponse) GetSessions() []*UserSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *SessionsResponse) GetCurrentSessionId() int64 {
	if x != nil {
		return x.CurrentSessionId
	}
	return 0
}

type RevokeSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"sessionId"
	SessionId     uint64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"sessionId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{41}
}

func (x *RevokeSessionRequest) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_user_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{42}
}

type RevokeAllSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"currentPassword"
	CurrentPassword string `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"currentPassword"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeAllSessionsRequest) Reset() {
	*x = RevokeAllSessionsRequest{}
	mi := &file_user_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllSessionsRequest) ProtoMessage() {}

func (x *RevokeAllSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllSessionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllSessionsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{43}
}

func (x *RevokeAllSessionsRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

type RevokeAllSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllSessionsResponse) Reset() {
	*x = RevokeAllSessionsResponse{}
	mi := &file_user_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllSessionsResponse) ProtoMessage() {}

func (x *RevokeAllSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllSessionsResponse.ProtoReflect.Descriptor instead.
func (*RevokeAllSessionsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{44}
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\rtwoto.user.v1\"N\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x85\x02\n" +
	"\vUserProfile\x12\x1b\n" +
	"\tpet_stage\x18\x01 \x01(\tR\bpetStage\x120\n" +
	"\x14interested_pet_types\x18\x02 \x03(\tR\x12interestedPetTypes\x12%\n" +
	"\x0epet_experience\x18\x03 \x01(\tR\rpetExperience\x12,\n" +
	"\x12daily_company_time\x18\x04 \x01(\tR\x10dailyCompanyTime\x12)\n" +
	"\x10living_situation\x18\x05 \x01(\tR\x0flivingSituation\x12'\n" +
	"\x0fpet_constraints\x18\x06 \x03(\tR\x0epetConstraints\"\xae\x01\n" +
	"\fUserIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\ridentity_type\x18\x02 \x01(\tR\fidentityType\x12%\n" +
	"\x0eidentity_value\x18\x03 \x01(\tR\ridentityValue\x12!\n" +
	"\fmasked_value\x18\x04 \x01(\tR\vmaskedValue\x12\x1f\n" +
	"\vverify_time\x18\x05 \x01(\x03R\n" +
	"verifyTime\"\xbb\x01\n" +
	"\vUserSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12(\n" +
	"\x10last_active_time\x18\x04 \x01(\x03R\x0elastActiveTime\x12\x1f\n" +
	"\vexpire_time\x18\x05 \x01(\x03R\n" +
	"expireTime\x12\x18\n" +
	"\acurrent\x18\x06 \x01(\bR\acurrent\"\x10\n" +
	"\x0eCaptchaRequest\"r\n" +
	"\x0fCaptchaResponse\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x01 \x01(\tR\tcaptchaId\x12!\n" +
	"\fimage_base64\x18\x02 \x01(\tR\vimageBase64\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"\x9e\x01\n" +
	"\x0fSendCodeRequest\x12\x1b\n" +
	"\tcode_type\x18\x01 \x01(\tR\bcodeType\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x04 \x01(\tR\tcaptchaId\x12!\n" +
	"\fcaptcha_code\x18\x05 \x01(\tR\vcaptchaCode\"\\\n" +
	"\x10SendCodeResponse\x12)\n" +
	"\x10cooldown_seconds\x18\x01 \x01(\x03R\x0fcooldownSeconds\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"\x87\x01\n" +
	"\x11EmailLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"captcha_id\x18\x03 \x01(\tR\tcaptchaId\x12!\n" +
	"\fcaptcha_code\x18\x04 \x01(\tR\vcaptchaCode\"\xf9\x01\n" +
	"\x12EmailLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_in\x18\x02 \x01(\x03R\x14accessTokenExpiresIn\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_in\x18\x04 \x01(\x03R\x15refreshTokenExpiresIn\x12+\n" +
	"\x04user\x18\x05 \x01(\v2\x17.twoto.user.v1.UserInfoR\x04user\"D\n" +
	"\x11PhoneLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x19\n" +
	"\bsms_code\x18\x02 \x01(\tR\asmsCode\"m\n" +
	"\x1aEmailRegisterVerifyRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"email_code\x18\x03 \x01(\tR\temailCode\"M\n" +
	"\x1bEmailRegisterVerifyResponse\x12.\n" +
	"\x13profile_setup_token\x18\x01 \x01(\tR\x11profileSetupToken\"\xdc\x02\n" +
	"\x16CompleteProfileRequest\x12.\n" +
	"\x13profile_setup_token\x18\x01 \x01(\tR\x11profileSetupToken\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1b\n" +
	"\tpet_stage\x18\x03 \x01(\tR\bpetStage\x120\n" +
	"\x14interested_pet_types\x18\x04 \x03(\tR\x12interestedPetTypes\x12%\n" +
	"\x0epet_experience\x18\x05 \x01(\tR\rpetExperience\x12,\n" +
	"\x12daily_company_time\x18\x06 \x01(\tR\x10dailyCompanyTime\x12)\n" +
	"\x10living_situation\x18\a \x01(\tR\x0flivingSituation\x12'\n" +
	"\x0fpet_constraints\x18\b \x03(\tR\x0epetConstraints\"\xfe\x01\n" +
	"\x17CompleteProfileResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_in\x18\x02 \x01(\x03R\x14accessTokenExpiresIn\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_in\x18\x04 \x01(\x03R\x15refreshTokenExpiresIn\x12+\n" +
	"\x04user\x18\x05 \x01(\v2\x17.twoto.user.v1.UserInfoR\x04user\"\xf4\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_in\x18\x02 \x01(\x03R\x14accessTokenExpiresIn\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_in\x18\x04 \x01(\x03R\x15refreshTokenExpiresIn\x12+\n" +
	"\x04user\x18\x05 \x01(\v2\x17.twoto.user.v1.UserInfoR\x04user\"\xac\x01\n" +
	"\x12PhoneLoginResponse\x124\n" +
	"\x16requires_profile_setup\x18\x01 \x01(\bR\x14requiresProfileSetup\x12.\n" +
	"\x13profile_setup_token\x18\x02 \x01(\tR\x11profileSetupToken\x120\n" +
	"\x04auth\x18\x03 \x01(\v2\x1c.twoto.user.v1.LoginResponseR\x04auth\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xc9\x01\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x125\n" +
	"\x17access_token_expires_in\x18\x02 \x01(\x03R\x14accessTokenExpiresIn\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x127\n" +
	"\x18refresh_token_expires_in\x18\x04 \x01(\x03R\x15refreshTokenExpiresIn\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x10\n" +
	"\x0eLogoutResponse\"\x81\x01\n" +
	"\x1fForgotPasswordVerifyCodeRequest\x12#\n" +
	"\ridentity_type\x18\x01 \x01(\tR\fidentityType\x12%\n" +
	"\x0eidentity_value\x18\x02 \x01(\tR\ridentityValue\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"C\n" +
	" ForgotPasswordVerifyCodeResponse\x12\x1f\n" +
	"\vreset_token\x18\x01 \x01(\tR\n" +
	"resetToken\"`\n" +
	"\x1aForgotPasswordResetRequest\x12\x1f\n" +
	"\vreset_token\x18\x01 \x01(\tR\n" +
	"resetToken\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x1d\n" +
	"\x1bForgotPasswordResetResponse\"\x12\n" +
	"\x10AccountMeRequest\"\xb3\x01\n" +
	"\x11AccountMeResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.twoto.user.v1.UserInfoR\x04user\x124\n" +
	"\aprofile\x18\x02 \x01(\v2\x1a.twoto.user.v1.UserProfileR\aprofile\x12;\n" +
	"\n" +
	"identities\x18\x03 \x03(\v2\x1b.twoto.user.v1.UserIdentityR\n" +
	"identities\"\xaa\x02\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1b\n" +
	"\tpet_stage\x18\x02 \x01(\tR\bpetStage\x120\n" +
	"\x14interested_pet_types\x18\x03 \x03(\tR\x12interestedPetTypes\x12%\n" +
	"\x0epet_experience\x18\x04 \x01(\tR\rpetExperience\x12,\n" +
	"\x12daily_company_time\x18\x05 \x01(\tR\x10dailyCompanyTime\x12)\n" +
	"\x10living_situation\x18\x06 \x01(\tR\x0flivingSituation\x12'\n" +
	"\x0fpet_constraints\x18\a \x03(\tR\x0epetConstraints\"\xb7\x01\n" +
	"\x15UpdateProfileResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.twoto.user.v1.UserInfoR\x04user\x124\n" +
	"\aprofile\x18\x02 \x01(\v2\x1a.twoto.user.v1.UserProfileR\aprofile\x12;\n" +
	"\n" +
	"identities\x18\x03 \x03(\v2\x1b.twoto.user.v1.UserIdentityR\n" +
	"identities\"I\n" +
	"\x12UpdateEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"email_code\x18\x02 \x01(\tR\temailCode\"\x15\n" +
	"\x13UpdateEmailResponse\"E\n" +
	"\x12UpdatePhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x19\n" +
	"\bsms_code\x18\x02 \x01(\tR\asmsCode\"\x15\n" +
	"\x13UpdatePhoneResponse\"?\n" +
	"\x12UnbindEmailRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\"\x15\n" +
	"\x13UnbindEmailResponse\"?\n" +
	"\x12UnbindPhoneRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\"\x15\n" +
	"\x13UnbindPhoneResponse\"e\n" +
	"\x15UpdatePasswordRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16UpdatePasswordResponse\"\x11\n" +
	"\x0fSessionsRequest\"x\n" +
	"\x10SessionsResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x1a.twoto.user.v1.UserSessionR\bsessions\x12,\n" +
	"\x12current_session_id\x18\x02 \x01(\x03R\x10currentSessionId\"5\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\"\x17\n" +
	"\x15RevokeSessionResponse\"E\n" +
	"\x18RevokeAllSessionsRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\"\x1b\n" +
	"\x19RevokeAllSessionsResponseB/Z-github.com/zxh3032/two-to/backend/proto;protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_user_proto_goTypes = []any{
	(*UserInfo)(nil),                         // 0: twoto.user.v1.UserInfo
	(*UserProfile)(nil),                      // 1: twoto.user.v1.UserProfile
	(*UserIdentity)(nil),                     // 2: twoto.user.v1.UserIdentity
	(*UserSession)(nil),                      // 3: twoto.user.v1.UserSession
	(*CaptchaRequest)(nil),                   // 4: twoto.user.v1.CaptchaRequest
	(*CaptchaResponse)(nil),                  // 5: twoto.user.v1.CaptchaResponse
	(*SendCodeRequest)(nil),                  // 6: twoto.user.v1.SendCodeRequest
	(*SendCodeResponse)(nil),                 // 7: twoto.user.v1.SendCodeResponse
	(*EmailLoginRequest)(nil),                // 8: twoto.user.v1.EmailLoginRequest
	(*EmailLoginResponse)(nil),               // 9: twoto.user.v1.EmailLoginResponse
	(*PhoneLoginRequest)(nil),                // 10: twoto.user.v1.PhoneLoginRequest
	(*EmailRegisterVerifyRequest)(nil),       // 11: twoto.user.v1.EmailRegisterVerifyRequest
	(*EmailRegisterVerifyResponse)(nil),      // 12: twoto.user.v1.EmailRegisterVerifyResponse
	(*CompleteProfileRequest)(nil),           // 13: twoto.user.v1.CompleteProfileRequest
	(*CompleteProfileResponse)(nil),          // 14: twoto.user.v1.CompleteProfileResponse
	(*LoginResponse)(nil),                    // 15: twoto.user.v1.LoginResponse
	(*PhoneLoginResponse)(nil),               // 16: twoto.user.v1.PhoneLoginResponse
	(*RefreshRequest)(nil),                   // 17: twoto.user.v1.RefreshRequest
	(*RefreshResponse)(nil),                  // 18: twoto.user.v1.RefreshResponse
	(*LogoutRequest)(nil),                    // 19: twoto.user.v1.LogoutRequest
	(*LogoutResponse)(nil),                   // 20: twoto.user.v1.LogoutResponse
	(*ForgotPasswordVerifyCodeRequest)(nil),  // 21: twoto.user.v1.ForgotPasswordVerifyCodeRequest
	(*ForgotPasswordVerifyCodeResponse)(nil), // 22: twoto.user.v1.ForgotPasswordVerifyCodeResponse
	(*ForgotPasswordResetRequest)(nil),       // 23: twoto.user.v1.ForgotPasswordResetRequest
	(*ForgotPasswordResetResponse)(nil),      // 24: twoto.user.v1.ForgotPasswordResetResponse
	(*AccountMeRequest)(nil),                 // 25: twoto.user.v1.AccountMeRequest
	(*AccountMeResponse)(nil),                // 26: twoto.user.v1.AccountMeResponse
	(*UpdateProfileRequest)(nil),             // 27: twoto.user.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),            // 28: twoto.user.v1.UpdateProfileResponse
	(*UpdateEmailRequest)(nil),               // 29: twoto.user.v1.UpdateEmailRequest
	(*UpdateEmailResponse)(nil),              // 30: twoto.user.v1.UpdateEmailResponse
	(*UpdatePhoneRequest)(nil),               // 31: twoto.user.v1.UpdatePhoneRequest
	(*UpdatePhoneResponse)(nil),              // 32: twoto.user.v1.UpdatePhoneResponse
	(*UnbindEmailRequest)(nil),               // 33: twoto.user.v1.UnbindEmailRequest
	(*UnbindEmailResponse)(nil),              // 34: twoto.user.v1.UnbindEmailResponse
	(*UnbindPhoneRequest)(nil),               // 35: twoto.user.v1.UnbindPhoneRequest
	(*UnbindPhoneResponse)(nil),              // 36: twoto.user.v1.UnbindPhoneResponse
	(*UpdatePasswordRequest)(nil),            // 37: twoto.user.v1.UpdatePasswordRequest
	(*UpdatePasswordResponse)(nil),           // 38: twoto.user.v1.UpdatePasswordResponse
	(*SessionsRequest)(nil),                  // 39: twoto.user.v1.SessionsRequest
	(*SessionsResponse)(nil),                 // 40: twoto.user.v1.SessionsResponse
	(*RevokeSessionRequest)(nil),             // 41: twoto.user.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),            // 42: twoto.user.v1.RevokeSessionResponse
	(*RevokeAllSessionsRequest)(nil),         // 43: twoto.user.v1.RevokeAllSessionsRequest
	(*RevokeAllSessionsResponse)(nil),        // 44: twoto.user.v1.RevokeAllSessionsResponse
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: twoto.user.v1.EmailLoginResponse.user:type_name -> twoto.user.v1.UserInfo
	0,  // 1: twoto.user.v1.CompleteProfileResponse.user:type_name -> twoto.user.v1.UserInfo
	0,  // 2: twoto.user.v1.LoginResponse.user:type_name -> twoto.user.v1.UserInfo
	15, // 3: twoto.user.v1.PhoneLoginResponse.auth:type_name -> twoto.user.v1.LoginResponse
	0,  // 4: twoto.user.v1.AccountMeResponse.user:type_name -> twoto.user.v1.UserInfo
	1,  // 5: twoto.user.v1.AccountMeResponse.profile:type_name -> twoto.user.v1.UserProfile
	2,  // 6: twoto.user.v1.AccountMeResponse.identities:type_name -> twoto.user.v1.UserIdentity
	0,  // 7: twoto.user.v1.UpdateProfileResponse.user:type_name -> twoto.user.v1.UserInfo
	1,  // 8: twoto.user.v1.UpdateProfileResponse.profile:type_name -> twoto.user.v1.UserProfile
	2,  // 9: twoto.user.v1.UpdateProfileResponse.identities:type_name -> twoto.user.v1.UserIdentity
	3,  // 10: twoto.user.v1.SessionsResponse.sessions:type_name -> twoto.user.v1.UserSession
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
