// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: assessment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssessmentQuestionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"title"
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	// @inject_tag: json:"description"
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	// @inject_tag: json:"questionType"
	QuestionType string `protobuf:"bytes,4,opt,name=question_type,json=questionType,proto3" json:"questionType"`
	// @inject_tag: json:"options"
	Options       []*AssessmentOptionItem `protobuf:"bytes,5,rep,name=options,proto3" json:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentQuestionItem) Reset() {
	*x = AssessmentQuestionItem{}
	mi := &file_assessment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentQuestionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentQuestionItem) ProtoMessage() {}

func (x *AssessmentQuestionItem) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentQuestionItem.ProtoReflect.Descriptor instead.
func (*AssessmentQuestionItem) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{0}
}

func (x *AssessmentQuestionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssessmentQuestionItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AssessmentQuestionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AssessmentQuestionItem) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *AssessmentQuestionItem) GetOptions() []*AssessmentOptionItem {
	if x != nil {
		return x.Options
	}
	return nil
}

type AssessmentOptionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"value"
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value"`
	// @inject_tag: json:"label"
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label"`
	// @inject_tag: json:"description"
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentOptionItem) Reset() {
	*x = AssessmentOptionItem{}
	mi := &file_assessment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentOptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentOptionItem) ProtoMessage() {}

func (x *AssessmentOptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentOptionItem.ProtoReflect.Descriptor instead.
func (*AssessmentOptionItem) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{1}
}

func (x *AssessmentOptionItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AssessmentOptionItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AssessmentOptionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AssessmentAnswerItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"questionId"
	QuestionId int64 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"questionId"`
	// @inject_tag: json:"values"
	Values        []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentAnswerItem) Reset() {
	*x = AssessmentAnswerItem{}
	mi := &file_assessment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentAnswerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentAnswerItem) ProtoMessage() {}

func (x *AssessmentAnswerItem) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentAnswerItem.ProtoReflect.Descriptor instead.
func (*AssessmentAnswerItem) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{2}
}

func (x *AssessmentAnswerItem) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *AssessmentAnswerItem) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type AssessmentResultItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"userId"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"userId"`
	// @inject_tag: json:"summary"
	Summary string `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary"`
	// @inject_tag: json:"recommendedBreedIds"
	RecommendedBreedIds []int64 `protobuf:"varint,4,rep,packed,name=recommended_breed_ids,json=recommendedBreedIds,proto3" json:"recommendedBreedIds"`
	// @inject_tag: json:"createdAt"
	CreatedAt     int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentResultItem) Reset() {
	*x = AssessmentResultItem{}
	mi := &file_assessment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentResultItem) ProtoMessage() {}

func (x *AssessmentResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentResultItem.ProtoReflect.Descriptor instead.
func (*AssessmentResultItem) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{3}
}

func (x *AssessmentResultItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssessmentResultItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssessmentResultItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AssessmentResultItem) GetRecommendedBreedIds() []int64 {
	if x != nil {
		return x.RecommendedBreedIds
	}
	return nil
}

func (x *AssessmentResultItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AssessmentQuestionListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"petType"
	PetType       string `protobuf:"bytes,1,opt,name=pet_type,json=petType,proto3" json:"petType"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentQuestionListRequest) Reset() {
	*x = AssessmentQuestionListRequest{}
	mi := &file_assessment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentQuestionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentQuestionListRequest) ProtoMessage() {}

func (x *AssessmentQuestionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentQuestionListRequest.ProtoReflect.Descriptor instead.
func (*AssessmentQuestionListRequest) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{4}
}

func (x *AssessmentQuestionListRequest) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

type AssessmentQuestionListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"data"
	Data          []*AssessmentQuestionItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentQuestionListResponse) Reset() {
	*x = AssessmentQuestionListResponse{}
	mi := &file_assessment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentQuestionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentQuestionListResponse) ProtoMessage() {}

func (x *AssessmentQuestionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentQuestionListResponse.ProtoReflect.Descriptor instead.
func (*AssessmentQuestionListResponse) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{5}
}

func (x *AssessmentQuestionListResponse) GetData() []*AssessmentQuestionItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type AssessmentSubmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"userId"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	// @inject_tag: json:"petType"
	PetType string `protobuf:"bytes,2,opt,name=pet_type,json=petType,proto3" json:"petType"`
	// @inject_tag: json:"answers"
	Answers       []*AssessmentAnswerItem `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentSubmitRequest) Reset() {
	*x = AssessmentSubmitRequest{}
	mi := &file_assessment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentSubmitRequest) ProtoMessage() {}

func (x *AssessmentSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentSubmitRequest.ProtoReflect.Descriptor instead.
func (*AssessmentSubmitRequest) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{6}
}

func (x *AssessmentSubmitRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssessmentSubmitRequest) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

func (x *AssessmentSubmitRequest) GetAnswers() []*AssessmentAnswerItem {
	if x != nil {
		return x.Answers
	}
	return nil
}

type AssessmentSubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"result"
	Result        *AssessmentResultItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentSubmitResponse) Reset() {
	*x = AssessmentSubmitResponse{}
	mi := &file_assessment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentSubmitResponse) ProtoMessage() {}

func (x *AssessmentSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentSubmitResponse.ProtoReflect.Descriptor instead.
func (*AssessmentSubmitResponse) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{7}
}

func (x *AssessmentSubmitResponse) GetResult() *AssessmentResultItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type AssessmentResultDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"userId"
	UserId        int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"userId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentResultDetailRequest) Reset() {
	*x = AssessmentResultDetailRequest{}
	mi := &file_assessment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentResultDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentResultDetailRequest) ProtoMessage() {}

func (x *AssessmentResultDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentResultDetailRequest.ProtoReflect.Descriptor instead.
func (*AssessmentResultDetailRequest) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{8}
}

func (x *AssessmentResultDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssessmentResultDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AssessmentResultDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"result"
	Result        *AssessmentResultItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentResultDetailResponse) Reset() {
	*x = AssessmentResultDetailResponse{}
	mi := &file_assessment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentResultDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentResultDetailResponse) ProtoMessage() {}

func (x *AssessmentResultDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentResultDetailResponse.ProtoReflect.Descriptor instead.
func (*AssessmentResultDetailResponse) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{9}
}

func (x *AssessmentResultDetailResponse) GetResult() *AssessmentResultItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type AssessmentHistoryListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"userId"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	// @inject_tag: json:"page"
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentHistoryListRequest) Reset() {
	*x = AssessmentHistoryListRequest{}
	mi := &file_assessment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentHistoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentHistoryListRequest) ProtoMessage() {}

func (x *AssessmentHistoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentHistoryListRequest.ProtoReflect.Descriptor instead.
func (*AssessmentHistoryListRequest) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{10}
}

func (x *AssessmentHistoryListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssessmentHistoryListRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type AssessmentHistoryListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"page"
	Page *PageMeta `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"data"
	Data          []*AssessmentResultItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssessmentHistoryListResponse) Reset() {
	*x = AssessmentHistoryListResponse{}
	mi := &file_assessment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssessmentHistoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessmentHistoryListResponse) ProtoMessage() {}

func (x *AssessmentHistoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assessment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessmentHistoryListResponse.ProtoReflect.Descriptor instead.
func (*AssessmentHistoryListResponse) Descriptor() ([]byte, []int) {
	return file_assessment_proto_rawDescGZIP(), []int{11}
}

func (x *AssessmentHistoryListResponse) GetPage() *PageMeta {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *AssessmentHistoryListResponse) GetData() []*AssessmentResultItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_assessment_proto protoreflect.FileDescriptor

const file_assessment_proto_rawDesc = "" +
	"\n" +
	"\x10assessment.proto\x12\x13twoto.assessment.v1\x1a\fcommon.proto\"\xca\x01\n" +
	"\x16AssessmentQuestionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rquestion_type\x18\x04 \x01(\tR\fquestionType\x12C\n" +
	"\aoptions\x18\x05 \x03(\v2).twoto.assessment.v1.AssessmentOptionItemR\aoptions\"d\n" +
	"\x14AssessmentOptionItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"O\n" +
	"\x14AssessmentAnswerItem\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\xac\x01\n" +
	"\x14AssessmentResultItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x122\n" +
	"\x15recommended_breed_ids\x18\x04 \x03(\x03R\x13recommendedBreedIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\":\n" +
	"\x1dAssessmentQuestionListRequest\x12\x19\n" +
	"\bpet_type\x18\x01 \x01(\tR\apetType\"a\n" +
	"\x1eAssessmentQuestionListResponse\x12?\n" +
	"\x04data\x18\x01 \x03(\v2+.twoto.assessment.v1.AssessmentQuestionItemR\x04data\"\x92\x01\n" +
	"\x17AssessmentSubmitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bpet_type\x18\x02 \x01(\tR\apetType\x12C\n" +
	"\aanswers\x18\x03 \x03(\v2).twoto.assessment.v1.AssessmentAnswerItemR\aanswers\"]\n" +
	"\x18AssessmentSubmitResponse\x12A\n" +
	"\x06result\x18\x01 \x01(\v2).twoto.assessment.v1.AssessmentResultItemR\x06result\"H\n" +
	"\x1dAssessmentResultDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"c\n" +
	"\x1eAssessmentResultDetailResponse\x12A\n" +
	"\x06result\x18\x01 \x01(\v2).twoto.assessment.v1.AssessmentResultItemR\x06result\"i\n" +
	"\x1cAssessmentHistoryListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x120\n" +
	"\x04page\x18\x02 \x01(\v2\x1c.twoto.common.v1.PageRequestR\x04page\"\x8d\x01\n" +
	"\x1dAssessmentHistoryListResponse\x12-\n" +
	"\x04page\x18\x01 \x01(\v2\x19.twoto.common.v1.PageMetaR\x04page\x12=\n" +
	"\x04data\x18\x02 \x03(\v2).twoto.assessment.v1.AssessmentResultItemR\x04dataB4Z2github.com/zxh3032/two-to/services/api/proto;protob\x06proto3"

var (
	file_assessment_proto_rawDescOnce sync.Once
	file_assessment_proto_rawDescData []byte
)

func file_assessment_proto_rawDescGZIP() []byte {
	file_assessment_proto_rawDescOnce.Do(func() {
		file_assessment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assessment_proto_rawDesc), len(file_assessment_proto_rawDesc)))
	})
	return file_assessment_proto_rawDescData
}

var file_assessment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_assessment_proto_goTypes = []any{
	(*AssessmentQuestionItem)(nil),         // 0: twoto.assessment.v1.AssessmentQuestionItem
	(*AssessmentOptionItem)(nil),           // 1: twoto.assessment.v1.AssessmentOptionItem
	(*AssessmentAnswerItem)(nil),           // 2: twoto.assessment.v1.AssessmentAnswerItem
	(*AssessmentResultItem)(nil),           // 3: twoto.assessment.v1.AssessmentResultItem
	(*AssessmentQuestionListRequest)(nil),  // 4: twoto.assessment.v1.AssessmentQuestionListRequest
	(*AssessmentQuestionListResponse)(nil), // 5: twoto.assessment.v1.AssessmentQuestionListResponse
	(*AssessmentSubmitRequest)(nil),        // 6: twoto.assessment.v1.AssessmentSubmitRequest
	(*AssessmentSubmitResponse)(nil),       // 7: twoto.assessment.v1.AssessmentSubmitResponse
	(*AssessmentResultDetailRequest)(nil),  // 8: twoto.assessment.v1.AssessmentResultDetailRequest
	(*AssessmentResultDetailResponse)(nil), // 9: twoto.assessment.v1.AssessmentResultDetailResponse
	(*AssessmentHistoryListRequest)(nil),   // 10: twoto.assessment.v1.AssessmentHistoryListRequest
	(*AssessmentHistoryListResponse)(nil),  // 11: twoto.assessment.v1.AssessmentHistoryListResponse
	(*PageRequest)(nil),                    // 12: twoto.common.v1.PageRequest
	(*PageMeta)(nil),                       // 13: twoto.common.v1.PageMeta
}
var file_assessment_proto_depIdxs = []int32{
	1,  // 0: twoto.assessment.v1.AssessmentQuestionItem.options:type_name -> twoto.assessment.v1.AssessmentOptionItem
	0,  // 1: twoto.assessment.v1.AssessmentQuestionListResponse.data:type_name -> twoto.assessment.v1.AssessmentQuestionItem
	2,  // 2: twoto.assessment.v1.AssessmentSubmitRequest.answers:type_name -> twoto.assessment.v1.AssessmentAnswerItem
	3,  // 3: twoto.assessment.v1.AssessmentSubmitResponse.result:type_name -> twoto.assessment.v1.AssessmentResultItem
	3,  // 4: twoto.assessment.v1.AssessmentResultDetailResponse.result:type_name -> twoto.assessment.v1.AssessmentResultItem
	12, // 5: twoto.assessment.v1.AssessmentHistoryListRequest.page:type_name -> twoto.common.v1.PageRequest
	13, // 6: twoto.assessment.v1.AssessmentHistoryListResponse.page:type_name -> twoto.common.v1.PageMeta
	3,  // 7: twoto.assessment.v1.AssessmentHistoryListResponse.data:type_name -> twoto.assessment.v1.AssessmentResultItem
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_assessment_proto_init() }
func file_assessment_proto_init() {
	if File_assessment_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assessment_proto_rawDesc), len(file_assessment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assessment_proto_goTypes,
		DependencyIndexes: file_assessment_proto_depIdxs,
		MessageInfos:      file_assessment_proto_msgTypes,
	}.Build()
	File_assessment_proto = out.File
	file_assessment_proto_goTypes = nil
	file_assessment_proto_depIdxs = nil
}
