// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: breed.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BreedItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"petType"
	PetType string `protobuf:"bytes,3,opt,name=pet_type,json=petType,proto3" json:"petType"`
	// @inject_tag: json:"summary"
	Summary string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary"`
	// @inject_tag: json:"temperament"
	Temperament string `protobuf:"bytes,5,opt,name=temperament,proto3" json:"temperament"`
	// @inject_tag: json:"careLevel"
	CareLevel string `protobuf:"bytes,6,opt,name=care_level,json=careLevel,proto3" json:"careLevel"`
	// @inject_tag: json:"activityLevel"
	ActivityLevel string `protobuf:"bytes,7,opt,name=activity_level,json=activityLevel,proto3" json:"activityLevel"`
	// @inject_tag: json:"tags"
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags"`
	// @inject_tag: json:"coverImage"
	CoverImage    string `protobuf:"bytes,9,opt,name=cover_image,json=coverImage,proto3" json:"coverImage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreedItem) Reset() {
	*x = BreedItem{}
	mi := &file_breed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreedItem) ProtoMessage() {}

func (x *BreedItem) ProtoReflect() protoreflect.Message {
	mi := &file_breed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreedItem.ProtoReflect.Descriptor instead.
func (*BreedItem) Descriptor() ([]byte, []int) {
	return file_breed_proto_rawDescGZIP(), []int{0}
}

func (x *BreedItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BreedItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BreedItem) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

func (x *BreedItem) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *BreedItem) GetTemperament() string {
	if x != nil {
		return x.Temperament
	}
	return ""
}

func (x *BreedItem) GetCareLevel() string {
	if x != nil {
		return x.CareLevel
	}
	return ""
}

func (x *BreedItem) GetActivityLevel() string {
	if x != nil {
		return x.ActivityLevel
	}
	return ""
}

func (x *BreedItem) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BreedItem) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

type BreedListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"petType"
	PetType string `protobuf:"bytes,1,opt,name=pet_type,json=petType,proto3" json:"petType"`
	// @inject_tag: json:"keyword"
	Keyword string `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword"`
	// @inject_tag: json:"tags"
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags"`
	// @inject_tag: json:"page"
	Page          *PageRequest `protobuf:"bytes,4,opt,name=page,proto3" json:"page"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreedListRequest) Reset() {
	*x = BreedListRequest{}
	mi := &file_breed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreedListRequest) ProtoMessage() {}

func (x *BreedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreedListRequest.ProtoReflect.Descriptor instead.
func (*BreedListRequest) Descriptor() ([]byte, []int) {
	return file_breed_proto_rawDescGZIP(), []int{1}
}

func (x *BreedListRequest) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

func (x *BreedListRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *BreedListRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BreedListRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type BreedListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"page"
	Page *PageMeta `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"data"
	Data          []*BreedItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreedListResponse) Reset() {
	*x = BreedListResponse{}
	mi := &file_breed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreedListResponse) ProtoMessage() {}

func (x *BreedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreedListResponse.ProtoReflect.Descriptor instead.
func (*BreedListResponse) Descriptor() ([]byte, []int) {
	return file_breed_proto_rawDescGZIP(), []int{2}
}

func (x *BreedListResponse) GetPage() *PageMeta {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *BreedListResponse) GetData() []*BreedItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type BreedDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreedDetailRequest) Reset() {
	*x = BreedDetailRequest{}
	mi := &file_breed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreedDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreedDetailRequest) ProtoMessage() {}

func (x *BreedDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_breed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreedDetailRequest.ProtoReflect.Descriptor instead.
func (*BreedDetailRequest) Descriptor() ([]byte, []int) {
	return file_breed_proto_rawDescGZIP(), []int{3}
}

func (x *BreedDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BreedDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"item"
	Item          *BreedItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BreedDetailResponse) Reset() {
	*x = BreedDetailResponse{}
	mi := &file_breed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BreedDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreedDetailResponse) ProtoMessage() {}

func (x *BreedDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_breed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreedDetailResponse.ProtoReflect.Descriptor instead.
func (*BreedDetailResponse) Descriptor() ([]byte, []int) {
	return file_breed_proto_rawDescGZIP(), []int{4}
}

func (x *BreedDetailResponse) GetItem() *BreedItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_breed_proto protoreflect.FileDescriptor

const file_breed_proto_rawDesc = "" +
	"\n" +
	"\vbreed.proto\x12\x0etwoto.breed.v1\x1a\fcommon.proto\"\x81\x02\n" +
	"\tBreedItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bpet_type\x18\x03 \x01(\tR\apetType\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12 \n" +
	"\vtemperament\x18\x05 \x01(\tR\vtemperament\x12\x1d\n" +
	"\n" +
	"care_level\x18\x06 \x01(\tR\tcareLevel\x12%\n" +
	"\x0eactivity_level\x18\a \x01(\tR\ractivityLevel\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1f\n" +
	"\vcover_image\x18\t \x01(\tR\n" +
	"coverImage\"\x8d\x01\n" +
	"\x10BreedListRequest\x12\x19\n" +
	"\bpet_type\x18\x01 \x01(\tR\apetType\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x120\n" +
	"\x04page\x18\x04 \x01(\v2\x1c.twoto.common.v1.PageRequestR\x04page\"q\n" +
	"\x11BreedListResponse\x12-\n" +
	"\x04page\x18\x01 \x01(\v2\x19.twoto.common.v1.PageMetaR\x04page\x12-\n" +
	"\x04data\x18\x02 \x03(\v2\x19.twoto.breed.v1.BreedItemR\x04data\"$\n" +
	"\x12BreedDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x13BreedDetailResponse\x12-\n" +
	"\x04item\x18\x01 \x01(\v2\x19.twoto.breed.v1.BreedItemR\x04itemB4Z2github.com/zxh3032/two-to/services/api/proto;protob\x06proto3"

var (
	file_breed_proto_rawDescOnce sync.Once
	file_breed_proto_rawDescData []byte
)

func file_breed_proto_rawDescGZIP() []byte {
	file_breed_proto_rawDescOnce.Do(func() {
		file_breed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_breed_proto_rawDesc), len(file_breed_proto_rawDesc)))
	})
	return file_breed_proto_rawDescData
}

var file_breed_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_breed_proto_goTypes = []any{
	(*BreedItem)(nil),           // 0: twoto.breed.v1.BreedItem
	(*BreedListRequest)(nil),    // 1: twoto.breed.v1.BreedListRequest
	(*BreedListResponse)(nil),   // 2: twoto.breed.v1.BreedListResponse
	(*BreedDetailRequest)(nil),  // 3: twoto.breed.v1.BreedDetailRequest
	(*BreedDetailResponse)(nil), // 4: twoto.breed.v1.BreedDetailResponse
	(*PageRequest)(nil),         // 5: twoto.common.v1.PageRequest
	(*PageMeta)(nil),            // 6: twoto.common.v1.PageMeta
}
var file_breed_proto_depIdxs = []int32{
	5, // 0: twoto.breed.v1.BreedListRequest.page:type_name -> twoto.common.v1.PageRequest
	6, // 1: twoto.breed.v1.BreedListResponse.page:type_name -> twoto.common.v1.PageMeta
	0, // 2: twoto.breed.v1.BreedListResponse.data:type_name -> twoto.breed.v1.BreedItem
	0, // 3: twoto.breed.v1.BreedDetailResponse.item:type_name -> twoto.breed.v1.BreedItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_breed_proto_init() }
func file_breed_proto_init() {
	if File_breed_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_breed_proto_rawDesc), len(file_breed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_breed_proto_goTypes,
		DependencyIndexes: file_breed_proto_depIdxs,
		MessageInfos:      file_breed_proto_msgTypes,
	}.Build()
	File_breed_proto = out.File
	file_breed_proto_goTypes = nil
	file_breed_proto_depIdxs = nil
}
