// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: care.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CareReminderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"petId"
	PetId int64 `protobuf:"varint,2,opt,name=pet_id,json=petId,proto3" json:"petId"`
	// @inject_tag: json:"reminderType"
	ReminderType string `protobuf:"bytes,3,opt,name=reminder_type,json=reminderType,proto3" json:"reminderType"`
	// @inject_tag: json:"title"
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title"`
	// @inject_tag: json:"description"
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	// @inject_tag: json:"scheduledAt"
	ScheduledAt int64 `protobuf:"varint,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduledAt"`
	// @inject_tag: json:"completedAt"
	CompletedAt int64 `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completedAt"`
	// @inject_tag: json:"status"
	Status        string `protobuf:"bytes,8,opt,name=status,proto3" json:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareReminderItem) Reset() {
	*x = CareReminderItem{}
	mi := &file_care_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareReminderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareReminderItem) ProtoMessage() {}

func (x *CareReminderItem) ProtoReflect() protoreflect.Message {
	mi := &file_care_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareReminderItem.ProtoReflect.Descriptor instead.
func (*CareReminderItem) Descriptor() ([]byte, []int) {
	return file_care_proto_rawDescGZIP(), []int{0}
}

func (x *CareReminderItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CareReminderItem) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *CareReminderItem) GetReminderType() string {
	if x != nil {
		return x.ReminderType
	}
	return ""
}

func (x *CareReminderItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CareReminderItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CareReminderItem) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *CareReminderItem) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *CareReminderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CareReminderCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"item"
	Item          *CareReminderItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareReminderCreateRequest) Reset() {
	*x = CareReminderCreateRequest{}
	mi := &file_care_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareReminderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareReminderCreateRequest) ProtoMessage() {}

func (x *CareReminderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_care_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareReminderCreateRequest.ProtoReflect.Descriptor instead.
func (*CareReminderCreateRequest) Descriptor() ([]byte, []int) {
	return file_care_proto_rawDescGZIP(), []int{1}
}

func (x *CareReminderCreateRequest) GetItem() *CareReminderItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CareReminderCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"item"
	Item          *CareReminderItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareReminderCreateResponse) Reset() {
	*x = CareReminderCreateResponse{}
	mi := &file_care_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareReminderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareReminderCreateResponse) ProtoMessage() {}

func (x *CareReminderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareReminderCreateResponse.ProtoReflect.Descriptor instead.
func (*CareReminderCreateResponse) Descriptor() ([]byte, []int) {
	return file_care_proto_rawDescGZIP(), []int{2}
}

func (x *CareReminderCreateResponse) GetItem() *CareReminderItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CareReminderListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"petId"
	PetId int64 `protobuf:"varint,1,opt,name=pet_id,json=petId,proto3" json:"petId"`
	// @inject_tag: json:"status"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
	// @inject_tag: json:"page"
	Page          *PageRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareReminderListRequest) Reset() {
	*x = CareReminderListRequest{}
	mi := &file_care_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareReminderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareReminderListRequest) ProtoMessage() {}

func (x *CareReminderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_care_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareReminderListRequest.ProtoReflect.Descriptor instead.
func (*CareReminderListRequest) Descriptor() ([]byte, []int) {
	return file_care_proto_rawDescGZIP(), []int{3}
}

func (x *CareReminderListRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *CareReminderListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CareReminderListRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type CareReminderListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"page"
	Page *PageMeta `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"data"
	Data          []*CareReminderItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareReminderListResponse) Reset() {
	*x = CareReminderListResponse{}
	mi := &file_care_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareReminderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareReminderListResponse) ProtoMessage() {}

func (x *CareReminderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareReminderListResponse.ProtoReflect.Descriptor instead.
func (*CareReminderListResponse) Descriptor() ([]byte, []int) {
	return file_care_proto_rawDescGZIP(), []int{4}
}

func (x *CareReminderListResponse) GetPage() *PageMeta {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *CareReminderListResponse) GetData() []*CareReminderItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type CareReminderCompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"petId"
	PetId         int64 `protobuf:"varint,2,opt,name=pet_id,json=petId,proto3" json:"petId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareReminderCompleteRequest) Reset() {
	*x = CareReminderCompleteRequest{}
	mi := &file_care_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareReminderCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareReminderCompleteRequest) ProtoMessage() {}

func (x *CareReminderCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_care_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareReminderCompleteRequest.ProtoReflect.Descriptor instead.
func (*CareReminderCompleteRequest) Descriptor() ([]byte, []int) {
	return file_care_proto_rawDescGZIP(), []int{5}
}

func (x *CareReminderCompleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CareReminderCompleteRequest) GetPetId() int64 {
	if x != nil {
		return x.PetId
	}
	return 0
}

type CareReminderCompleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"item"
	Item          *CareReminderItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CareReminderCompleteResponse) Reset() {
	*x = CareReminderCompleteResponse{}
	mi := &file_care_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CareReminderCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CareReminderCompleteResponse) ProtoMessage() {}

func (x *CareReminderCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_care_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CareReminderCompleteResponse.ProtoReflect.Descriptor instead.
func (*CareReminderCompleteResponse) Descriptor() ([]byte, []int) {
	return file_care_proto_rawDescGZIP(), []int{6}
}

func (x *CareReminderCompleteResponse) GetItem() *CareReminderItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_care_proto protoreflect.FileDescriptor

const file_care_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"care.proto\x12\rtwoto.care.v1\x1a\fcommon.proto\"\xf4\x01\n" +
	"\x10CareReminderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\x03R\x05petId\x12#\n" +
	"\rreminder_type\x18\x03 \x01(\tR\freminderType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\fscheduled_at\x18\x06 \x01(\x03R\vscheduledAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"P\n" +
	"\x19CareReminderCreateRequest\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.twoto.care.v1.CareReminderItemR\x04item\"Q\n" +
	"\x1aCareReminderCreateResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.twoto.care.v1.CareReminderItemR\x04item\"z\n" +
	"\x17CareReminderListRequest\x12\x15\n" +
	"\x06pet_id\x18\x01 \x01(\x03R\x05petId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x120\n" +
	"\x04page\x18\x03 \x01(\v2\x1c.twoto.common.v1.PageRequestR\x04page\"~\n" +
	"\x18CareReminderListResponse\x12-\n" +
	"\x04page\x18\x01 \x01(\v2\x19.twoto.common.v1.PageMetaR\x04page\x123\n" +
	"\x04data\x18\x02 \x03(\v2\x1f.twoto.care.v1.CareReminderItemR\x04data\"D\n" +
	"\x1bCareReminderCompleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06pet_id\x18\x02 \x01(\x03R\x05petId\"S\n" +
	"\x1cCareReminderCompleteResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.twoto.care.v1.CareReminderItemR\x04itemB4Z2github.com/zxh3032/two-to/services/api/proto;protob\x06proto3"

var (
	file_care_proto_rawDescOnce sync.Once
	file_care_proto_rawDescData []byte
)

func file_care_proto_rawDescGZIP() []byte {
	file_care_proto_rawDescOnce.Do(func() {
		file_care_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_care_proto_rawDesc), len(file_care_proto_rawDesc)))
	})
	return file_care_proto_rawDescData
}

var file_care_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_care_proto_goTypes = []any{
	(*CareReminderItem)(nil),             // 0: twoto.care.v1.CareReminderItem
	(*CareReminderCreateRequest)(nil),    // 1: twoto.care.v1.CareReminderCreateRequest
	(*CareReminderCreateResponse)(nil),   // 2: twoto.care.v1.CareReminderCreateResponse
	(*CareReminderListRequest)(nil),      // 3: twoto.care.v1.CareReminderListRequest
	(*CareReminderListResponse)(nil),     // 4: twoto.care.v1.CareReminderListResponse
	(*CareReminderCompleteRequest)(nil),  // 5: twoto.care.v1.CareReminderCompleteRequest
	(*CareReminderCompleteResponse)(nil), // 6: twoto.care.v1.CareReminderCompleteResponse
	(*PageRequest)(nil),                  // 7: twoto.common.v1.PageRequest
	(*PageMeta)(nil),                     // 8: twoto.common.v1.PageMeta
}
var file_care_proto_depIdxs = []int32{
	0, // 0: twoto.care.v1.CareReminderCreateRequest.item:type_name -> twoto.care.v1.CareReminderItem
	0, // 1: twoto.care.v1.CareReminderCreateResponse.item:type_name -> twoto.care.v1.CareReminderItem
	7, // 2: twoto.care.v1.CareReminderListRequest.page:type_name -> twoto.common.v1.PageRequest
	8, // 3: twoto.care.v1.CareReminderListResponse.page:type_name -> twoto.common.v1.PageMeta
	0, // 4: twoto.care.v1.CareReminderListResponse.data:type_name -> twoto.care.v1.CareReminderItem
	0, // 5: twoto.care.v1.CareReminderCompleteResponse.item:type_name -> twoto.care.v1.CareReminderItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_care_proto_init() }
func file_care_proto_init() {
	if File_care_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_care_proto_rawDesc), len(file_care_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_care_proto_goTypes,
		DependencyIndexes: file_care_proto_depIdxs,
		MessageInfos:      file_care_proto_msgTypes,
	}.Build()
	File_care_proto = out.File
	file_care_proto_goTypes = nil
	file_care_proto_depIdxs = nil
}
