// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: example.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExamplePetItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"petType"
	PetType string `protobuf:"bytes,3,opt,name=pet_type,json=petType,proto3" json:"petType"`
	// @inject_tag: json:"breedName"
	BreedName string `protobuf:"bytes,4,opt,name=breed_name,json=breedName,proto3" json:"breedName"`
	// @inject_tag: json:"birthday"
	Birthday      string `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamplePetItem) Reset() {
	*x = ExamplePetItem{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamplePetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamplePetItem) ProtoMessage() {}

func (x *ExamplePetItem) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamplePetItem.ProtoReflect.Descriptor instead.
func (*ExamplePetItem) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExamplePetItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExamplePetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExamplePetItem) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

func (x *ExamplePetItem) GetBreedName() string {
	if x != nil {
		return x.BreedName
	}
	return ""
}

func (x *ExamplePetItem) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

type ExamplePetDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"userId"
	UserId        int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"userId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamplePetDetailRequest) Reset() {
	*x = ExamplePetDetailRequest{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamplePetDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamplePetDetailRequest) ProtoMessage() {}

func (x *ExamplePetDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamplePetDetailRequest.ProtoReflect.Descriptor instead.
func (*ExamplePetDetailRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *ExamplePetDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExamplePetDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ExamplePetDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"item"
	Item          *ExamplePetItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamplePetDetailResponse) Reset() {
	*x = ExamplePetDetailResponse{}
	mi := &file_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamplePetDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamplePetDetailResponse) ProtoMessage() {}

func (x *ExamplePetDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamplePetDetailResponse.ProtoReflect.Descriptor instead.
func (*ExamplePetDetailResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

func (x *ExamplePetDetailResponse) GetItem() *ExamplePetItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\x10twoto.example.v1\"\x8a\x01\n" +
	"\x0eExamplePetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bpet_type\x18\x03 \x01(\tR\apetType\x12\x1d\n" +
	"\n" +
	"breed_name\x18\x04 \x01(\tR\tbreedName\x12\x1a\n" +
	"\bbirthday\x18\x05 \x01(\tR\bbirthday\"B\n" +
	"\x17ExamplePetDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"P\n" +
	"\x18ExamplePetDetailResponse\x124\n" +
	"\x04item\x18\x01 \x01(\v2 .twoto.example.v1.ExamplePetItemR\x04itemB4Z2github.com/zxh3032/two-to/services/api/proto;protob\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_proto_goTypes = []any{
	(*ExamplePetItem)(nil),           // 0: twoto.example.v1.ExamplePetItem
	(*ExamplePetDetailRequest)(nil),  // 1: twoto.example.v1.ExamplePetDetailRequest
	(*ExamplePetDetailResponse)(nil), // 2: twoto.example.v1.ExamplePetDetailResponse
}
var file_example_proto_depIdxs = []int32{
	0, // 0: twoto.example.v1.ExamplePetDetailResponse.item:type_name -> twoto.example.v1.ExamplePetItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
