// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: pet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetProfileItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"userId"
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"userId"`
	// @inject_tag: json:"name"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	// @inject_tag: json:"petType"
	PetType string `protobuf:"bytes,4,opt,name=pet_type,json=petType,proto3" json:"petType"`
	// @inject_tag: json:"breedId"
	BreedId int64 `protobuf:"varint,5,opt,name=breed_id,json=breedId,proto3" json:"breedId"`
	// @inject_tag: json:"gender"
	Gender string `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender"`
	// @inject_tag: json:"birthday"
	Birthday string `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday"`
	// @inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar"`
	// @inject_tag: json:"createdAt"
	CreatedAt int64 `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`
	// @inject_tag: json:"updatedAt"
	UpdatedAt     int64 `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetProfileItem) Reset() {
	*x = PetProfileItem{}
	mi := &file_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetProfileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetProfileItem) ProtoMessage() {}

func (x *PetProfileItem) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetProfileItem.ProtoReflect.Descriptor instead.
func (*PetProfileItem) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{0}
}

func (x *PetProfileItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PetProfileItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PetProfileItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PetProfileItem) GetPetType() string {
	if x != nil {
		return x.PetType
	}
	return ""
}

func (x *PetProfileItem) GetBreedId() int64 {
	if x != nil {
		return x.BreedId
	}
	return 0
}

func (x *PetProfileItem) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PetProfileItem) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *PetProfileItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PetProfileItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PetProfileItem) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PetCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profile"
	Profile       *PetProfileItem `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetCreateRequest) Reset() {
	*x = PetCreateRequest{}
	mi := &file_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetCreateRequest) ProtoMessage() {}

func (x *PetCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetCreateRequest.ProtoReflect.Descriptor instead.
func (*PetCreateRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{1}
}

func (x *PetCreateRequest) GetProfile() *PetProfileItem {
	if x != nil {
		return x.Profile
	}
	return nil
}

type PetCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profile"
	Profile       *PetProfileItem `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetCreateResponse) Reset() {
	*x = PetCreateResponse{}
	mi := &file_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetCreateResponse) ProtoMessage() {}

func (x *PetCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetCreateResponse.ProtoReflect.Descriptor instead.
func (*PetCreateResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{2}
}

func (x *PetCreateResponse) GetProfile() *PetProfileItem {
	if x != nil {
		return x.Profile
	}
	return nil
}

type PetUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profile"
	Profile       *PetProfileItem `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetUpdateRequest) Reset() {
	*x = PetUpdateRequest{}
	mi := &file_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetUpdateRequest) ProtoMessage() {}

func (x *PetUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetUpdateRequest.ProtoReflect.Descriptor instead.
func (*PetUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{3}
}

func (x *PetUpdateRequest) GetProfile() *PetProfileItem {
	if x != nil {
		return x.Profile
	}
	return nil
}

type PetUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profile"
	Profile       *PetProfileItem `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetUpdateResponse) Reset() {
	*x = PetUpdateResponse{}
	mi := &file_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetUpdateResponse) ProtoMessage() {}

func (x *PetUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetUpdateResponse.ProtoReflect.Descriptor instead.
func (*PetUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{4}
}

func (x *PetUpdateResponse) GetProfile() *PetProfileItem {
	if x != nil {
		return x.Profile
	}
	return nil
}

type PetDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"userId"
	UserId        int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"userId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDetailRequest) Reset() {
	*x = PetDetailRequest{}
	mi := &file_pet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDetailRequest) ProtoMessage() {}

func (x *PetDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDetailRequest.ProtoReflect.Descriptor instead.
func (*PetDetailRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{5}
}

func (x *PetDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PetDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PetDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profile"
	Profile       *PetProfileItem `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetDetailResponse) Reset() {
	*x = PetDetailResponse{}
	mi := &file_pet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetDetailResponse) ProtoMessage() {}

func (x *PetDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetDetailResponse.ProtoReflect.Descriptor instead.
func (*PetDetailResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{6}
}

func (x *PetDetailResponse) GetProfile() *PetProfileItem {
	if x != nil {
		return x.Profile
	}
	return nil
}

type PetListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"userId"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	// @inject_tag: json:"page"
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetListRequest) Reset() {
	*x = PetListRequest{}
	mi := &file_pet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetListRequest) ProtoMessage() {}

func (x *PetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetListRequest.ProtoReflect.Descriptor instead.
func (*PetListRequest) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{7}
}

func (x *PetListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PetListRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type PetListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"page"
	Page *PageMeta `protobuf:"bytes,1,opt,name=page,proto3" json:"page"`
	// @inject_tag: json:"data"
	Data          []*PetProfileItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PetListResponse) Reset() {
	*x = PetListResponse{}
	mi := &file_pet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PetListResponse) ProtoMessage() {}

func (x *PetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PetListResponse.ProtoReflect.Descriptor instead.
func (*PetListResponse) Descriptor() ([]byte, []int) {
	return file_pet_proto_rawDescGZIP(), []int{8}
}

func (x *PetListResponse) GetPage() *PageMeta {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PetListResponse) GetData() []*PetProfileItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pet_proto protoreflect.FileDescriptor

const file_pet_proto_rawDesc = "" +
	"\n" +
	"\tpet.proto\x12\ftwoto.pet.v1\x1a\fcommon.proto\"\x8d\x02\n" +
	"\x0ePetProfileItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bpet_type\x18\x04 \x01(\tR\apetType\x12\x19\n" +
	"\bbreed_id\x18\x05 \x01(\x03R\abreedId\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthday\x12\x16\n" +
	"\x06avatar\x18\b \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"J\n" +
	"\x10PetCreateRequest\x126\n" +
	"\aprofile\x18\x01 \x01(\v2\x1c.twoto.pet.v1.PetProfileItemR\aprofile\"K\n" +
	"\x11PetCreateResponse\x126\n" +
	"\aprofile\x18\x01 \x01(\v2\x1c.twoto.pet.v1.PetProfileItemR\aprofile\"J\n" +
	"\x10PetUpdateRequest\x126\n" +
	"\aprofile\x18\x01 \x01(\v2\x1c.twoto.pet.v1.PetProfileItemR\aprofile\"K\n" +
	"\x11PetUpdateResponse\x126\n" +
	"\aprofile\x18\x01 \x01(\v2\x1c.twoto.pet.v1.PetProfileItemR\aprofile\";\n" +
	"\x10PetDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"K\n" +
	"\x11PetDetailResponse\x126\n" +
	"\aprofile\x18\x01 \x01(\v2\x1c.twoto.pet.v1.PetProfileItemR\aprofile\"[\n" +
	"\x0ePetListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x120\n" +
	"\x04page\x18\x02 \x01(\v2\x1c.twoto.common.v1.PageRequestR\x04page\"r\n" +
	"\x0fPetListResponse\x12-\n" +
	"\x04page\x18\x01 \x01(\v2\x19.twoto.common.v1.PageMetaR\x04page\x120\n" +
	"\x04data\x18\x02 \x03(\v2\x1c.twoto.pet.v1.PetProfileItemR\x04dataB4Z2github.com/zxh3032/two-to/services/api/proto;protob\x06proto3"

var (
	file_pet_proto_rawDescOnce sync.Once
	file_pet_proto_rawDescData []byte
)

func file_pet_proto_rawDescGZIP() []byte {
	file_pet_proto_rawDescOnce.Do(func() {
		file_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)))
	})
	return file_pet_proto_rawDescData
}

var file_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pet_proto_goTypes = []any{
	(*PetProfileItem)(nil),    // 0: twoto.pet.v1.PetProfileItem
	(*PetCreateRequest)(nil),  // 1: twoto.pet.v1.PetCreateRequest
	(*PetCreateResponse)(nil), // 2: twoto.pet.v1.PetCreateResponse
	(*PetUpdateRequest)(nil),  // 3: twoto.pet.v1.PetUpdateRequest
	(*PetUpdateResponse)(nil), // 4: twoto.pet.v1.PetUpdateResponse
	(*PetDetailRequest)(nil),  // 5: twoto.pet.v1.PetDetailRequest
	(*PetDetailResponse)(nil), // 6: twoto.pet.v1.PetDetailResponse
	(*PetListRequest)(nil),    // 7: twoto.pet.v1.PetListRequest
	(*PetListResponse)(nil),   // 8: twoto.pet.v1.PetListResponse
	(*PageRequest)(nil),       // 9: twoto.common.v1.PageRequest
	(*PageMeta)(nil),          // 10: twoto.common.v1.PageMeta
}
var file_pet_proto_depIdxs = []int32{
	0,  // 0: twoto.pet.v1.PetCreateRequest.profile:type_name -> twoto.pet.v1.PetProfileItem
	0,  // 1: twoto.pet.v1.PetCreateResponse.profile:type_name -> twoto.pet.v1.PetProfileItem
	0,  // 2: twoto.pet.v1.PetUpdateRequest.profile:type_name -> twoto.pet.v1.PetProfileItem
	0,  // 3: twoto.pet.v1.PetUpdateResponse.profile:type_name -> twoto.pet.v1.PetProfileItem
	0,  // 4: twoto.pet.v1.PetDetailResponse.profile:type_name -> twoto.pet.v1.PetProfileItem
	9,  // 5: twoto.pet.v1.PetListRequest.page:type_name -> twoto.common.v1.PageRequest
	10, // 6: twoto.pet.v1.PetListResponse.page:type_name -> twoto.common.v1.PageMeta
	0,  // 7: twoto.pet.v1.PetListResponse.data:type_name -> twoto.pet.v1.PetProfileItem
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pet_proto_init() }
func file_pet_proto_init() {
	if File_pet_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pet_proto_rawDesc), len(file_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pet_proto_goTypes,
		DependencyIndexes: file_pet_proto_depIdxs,
		MessageInfos:      file_pet_proto_msgTypes,
	}.Build()
	File_pet_proto = out.File
	file_pet_proto_goTypes = nil
	file_pet_proto_depIdxs = nil
}
