// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfileItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @inject_tag: json:"nickname"
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname"`
	// @inject_tag: json:"avatar"
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	// @inject_tag: json:"createdAt"
	CreatedAt     int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"createdAt"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileItem) Reset() {
	*x = UserProfileItem{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileItem) ProtoMessage() {}

func (x *UserProfileItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileItem.ProtoReflect.Descriptor instead.
func (*UserProfileItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfileItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfileItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfileItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfileItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type UserPreferenceItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"livingSpace"
	LivingSpace string `protobuf:"bytes,1,opt,name=living_space,json=livingSpace,proto3" json:"livingSpace"`
	// @inject_tag: json:"dailyFreeTime"
	DailyFreeTime string `protobuf:"bytes,2,opt,name=daily_free_time,json=dailyFreeTime,proto3" json:"dailyFreeTime"`
	// @inject_tag: json:"activityLevel"
	ActivityLevel string `protobuf:"bytes,3,opt,name=activity_level,json=activityLevel,proto3" json:"activityLevel"`
	// @inject_tag: json:"careExperience"
	CareExperience string `protobuf:"bytes,4,opt,name=care_experience,json=careExperience,proto3" json:"careExperience"`
	// @inject_tag: json:"preferredPetTypes"
	PreferredPetTypes []string `protobuf:"bytes,5,rep,name=preferred_pet_types,json=preferredPetTypes,proto3" json:"preferredPetTypes"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserPreferenceItem) Reset() {
	*x = UserPreferenceItem{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferenceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferenceItem) ProtoMessage() {}

func (x *UserPreferenceItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferenceItem.ProtoReflect.Descriptor instead.
func (*UserPreferenceItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserPreferenceItem) GetLivingSpace() string {
	if x != nil {
		return x.LivingSpace
	}
	return ""
}

func (x *UserPreferenceItem) GetDailyFreeTime() string {
	if x != nil {
		return x.DailyFreeTime
	}
	return ""
}

func (x *UserPreferenceItem) GetActivityLevel() string {
	if x != nil {
		return x.ActivityLevel
	}
	return ""
}

func (x *UserPreferenceItem) GetCareExperience() string {
	if x != nil {
		return x.CareExperience
	}
	return ""
}

func (x *UserPreferenceItem) GetPreferredPetTypes() []string {
	if x != nil {
		return x.PreferredPetTypes
	}
	return nil
}

type UserProfileDetailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"userId"
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileDetailRequest) Reset() {
	*x = UserProfileDetailRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileDetailRequest) ProtoMessage() {}

func (x *UserProfileDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileDetailRequest.ProtoReflect.Descriptor instead.
func (*UserProfileDetailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfileDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserProfileDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"profile"
	Profile *UserProfileItem `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile"`
	// @inject_tag: json:"preference"
	Preference    *UserPreferenceItem `protobuf:"bytes,2,opt,name=preference,proto3" json:"preference"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileDetailResponse) Reset() {
	*x = UserProfileDetailResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileDetailResponse) ProtoMessage() {}

func (x *UserProfileDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileDetailResponse.ProtoReflect.Descriptor instead.
func (*UserProfileDetailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserProfileDetailResponse) GetProfile() *UserProfileItem {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *UserProfileDetailResponse) GetPreference() *UserPreferenceItem {
	if x != nil {
		return x.Preference
	}
	return nil
}

type UserPreferenceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"userId"
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	// @inject_tag: json:"preference"
	Preference    *UserPreferenceItem `protobuf:"bytes,2,opt,name=preference,proto3" json:"preference"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferenceUpdateRequest) Reset() {
	*x = UserPreferenceUpdateRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferenceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferenceUpdateRequest) ProtoMessage() {}

func (x *UserPreferenceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferenceUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserPreferenceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserPreferenceUpdateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserPreferenceUpdateRequest) GetPreference() *UserPreferenceItem {
	if x != nil {
		return x.Preference
	}
	return nil
}

type UserPreferenceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"preference"
	Preference    *UserPreferenceItem `protobuf:"bytes,1,opt,name=preference,proto3" json:"preference"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferenceUpdateResponse) Reset() {
	*x = UserPreferenceUpdateResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferenceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferenceUpdateResponse) ProtoMessage() {}

func (x *UserPreferenceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferenceUpdateResponse.ProtoReflect.Descriptor instead.
func (*UserPreferenceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserPreferenceUpdateResponse) GetPreference() *UserPreferenceItem {
	if x != nil {
		return x.Preference
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\rtwoto.user.v1\"\x8a\x01\n" +
	"\x0fUserProfileItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\"\xdf\x01\n" +
	"\x12UserPreferenceItem\x12!\n" +
	"\fliving_space\x18\x01 \x01(\tR\vlivingSpace\x12&\n" +
	"\x0fdaily_free_time\x18\x02 \x01(\tR\rdailyFreeTime\x12%\n" +
	"\x0eactivity_level\x18\x03 \x01(\tR\ractivityLevel\x12'\n" +
	"\x0fcare_experience\x18\x04 \x01(\tR\x0ecareExperience\x12.\n" +
	"\x13preferred_pet_types\x18\x05 \x03(\tR\x11preferredPetTypes\"3\n" +
	"\x18UserProfileDetailRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x98\x01\n" +
	"\x19UserProfileDetailResponse\x128\n" +
	"\aprofile\x18\x01 \x01(\v2\x1e.twoto.user.v1.UserProfileItemR\aprofile\x12A\n" +
	"\n" +
	"preference\x18\x02 \x01(\v2!.twoto.user.v1.UserPreferenceItemR\n" +
	"preference\"y\n" +
	"\x1bUserPreferenceUpdateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12A\n" +
	"\n" +
	"preference\x18\x02 \x01(\v2!.twoto.user.v1.UserPreferenceItemR\n" +
	"preference\"a\n" +
	"\x1cUserPreferenceUpdateResponse\x12A\n" +
	"\n" +
	"preference\x18\x01 \x01(\v2!.twoto.user.v1.UserPreferenceItemR\n" +
	"preferenceB4Z2github.com/zxh3032/two-to/services/api/proto;protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_proto_goTypes = []any{
	(*UserProfileItem)(nil),              // 0: twoto.user.v1.UserProfileItem
	(*UserPreferenceItem)(nil),           // 1: twoto.user.v1.UserPreferenceItem
	(*UserProfileDetailRequest)(nil),     // 2: twoto.user.v1.UserProfileDetailRequest
	(*UserProfileDetailResponse)(nil),    // 3: twoto.user.v1.UserProfileDetailResponse
	(*UserPreferenceUpdateRequest)(nil),  // 4: twoto.user.v1.UserPreferenceUpdateRequest
	(*UserPreferenceUpdateResponse)(nil), // 5: twoto.user.v1.UserPreferenceUpdateResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: twoto.user.v1.UserProfileDetailResponse.profile:type_name -> twoto.user.v1.UserProfileItem
	1, // 1: twoto.user.v1.UserProfileDetailResponse.preference:type_name -> twoto.user.v1.UserPreferenceItem
	1, // 2: twoto.user.v1.UserPreferenceUpdateRequest.preference:type_name -> twoto.user.v1.UserPreferenceItem
	1, // 3: twoto.user.v1.UserPreferenceUpdateResponse.preference:type_name -> twoto.user.v1.UserPreferenceItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
